// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.VersionInfo>;

export function GetVersionInfo():Promise<main.VersionInfo>;

export function Greet(arg1:string):Promise<string>;

export function SetVersionInfo(arg1:main.VersionInfo):Promise<void>;
