// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSettingsHandler() {
  return window['go']['main']['Backend']['AddSettingsHandler']();
}

export function AddUpdateHandler(arg1) {
  return window['go']['main']['Backend']['AddUpdateHandler'](arg1);
}

export function StartServer(arg1, arg2) {
  return window['go']['main']['Backend']['StartServer'](arg1, arg2);
}

export function StopServer() {
  return window['go']['main']['Backend']['StopServer']();
}
