// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function StartServer(arg1:context.Context):Promise<string>;

export function StopServer():Promise<string>;
