// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AddSettingsHandler():Promise<void>;

export function AddUpdateHandler(arg1:main.Updater):Promise<void>;

export function StartServer(arg1:context.Context,arg2:main.Updater):Promise<string>;

export function StopServer():Promise<string>;
